candy_list <- list(
  "almond joy bar" = c("almond joy",
                       "almond joys"),
  "babe ruth bar" = c("baby ruth"),
  "bit-o-honey" = c("bit o honey",
                    "bit o' honey",
                    "bit-o-honey"),
  "bonkers" = c("bonkers",
                "bonkers (the candy)"),
  "box'o'raisins" = c("box'o'raisins",
                      "box’o’ raisins"),
  "charleston chew" = c("charleston chew",
                        "charleston chews"),
  "chick-o-sticks" = c("chick-o-sticks (we don’t know what that is)"),
  "free restaurant candy" = c("candy that is clearly just the stuff given out for free at restaurants"),
  "gummy bears" = c("gummy bears straight up"),
  "jolly rancher" = c("jolly rancher (bad flavor)",
                      "jolly ranchers (good flavor)"),
  "joyjoy" = c("joyjoy (mit iodine!)",
               "joyjoy (mit iodine)"),
  "kit kat bar" = c("kit kat"),
  "licorice" = c("licorice",
                 "licorice (not black)",
                 "licorice (yes black)"),
  "mary jane" = c("anonymous brown globs that come in black and orange wrappers",
                  "anonymous brown globs that come in black and orange wrappers	(a.k.a. mary janes)",
                  "mary janes"),
  "m&ms" = c("blue m&m's",
             "green party m&m's",
             "independent m&m's",
             "mint m&ms",
             "peanut butter m&m's",
             "peanut butter m&ms",
             "peanut m&m’s",
             "red m&m's",
             "regular m&ms",
             "third party m&m's"),
  "mike and ike" = c("mike and ike",
                     "mike and ikes"),
  "mounds bar" = c("mounds",
                   "mounds bar"),
  "payday bar" = c("pay day",
                   "payday"),
  "popcorn ball" = c("popcorn ball",
                     "popcorn balls"),
  "raisinets" = c("raisinets",
                  "raisinettes"),
  "skor bar" = c("skor",
                 "skor bars"),
  "sky bar" = c("sky bar",
                "skybar"),
  "smarties" = c("smarties (american)",
                 "smarties (commonwealth)"),
  "snickers bar" = c("snickers"),
  "sour patch kids" = c("sour patch kids",
                        "sourpatch kids (i.e. abominations of nature)"),
  "sugar daddy" = c("sugar daddies",
                    "sugar daddy"),
  "sweetarts" = c("sweetarts",
                  "sweettarts",
                  "sweet tarts"),
  "sweetums" = c("sweetums",
                 "sweetums (a friend to diabetes)"),
  "take 5 bar" = c("take 5",
                   "take 5 bar",
                   "take 5 bars",
                   "take five",
                   "take5"),
  "toblerone bar" = c("tolberone something or other"),
  "tootsie roll" = c("tootsie roll",
                     "tootsie roll pops",
                     "tootsie rolls"),
  "twix bar" = c("twix"),
  "whatchamacallit bar" = c("whatchamacallit",
                            "whatchamacallit bars"),
  "zagnut bar" = c("zagnut"),
  "zero bar" = c("zero bar",
                 "zero bars")
)
