candy_names <- c(
  "100 grand bar",
  "abba zabba",
  "airheads",
  "almond joy bar",
  "andes mints",
  # "any full sized candy bar",
  "atomic fireballs",
  "babe ruth bar",
  "bit-o-honey",
  "black jacks",
  "blow pops",
  "bonkers",
  "bottle caps",
  "bounty",
  "box'o'raisins",
  "bubble gum",
  "butterfinger",
  "cadbury creme eggs",
  "candy apples",
  "candy cigarettes",
  "candy corn",
  "caramel apples",
  "caramellos",
  "caramels",
  "charleston chew",
  "chick-o-sticks",
  "chiclets",
  "coffee crisp",
  "crispy crunch",
  "dark chocolate",
  "dark chocolate hershey",
  "dots",
  "dove bars",
  "ferrero rocher",
  "free restaurant candy",
  "fun dip",
  "fuzzy peaches",
  "gobstoppers",
  "goo goo clusters",
  "good n' plenty",
  "gum from baseball cards",
  "gummy bears",
  "gummy worms",
  "hard candy",
  "heath bar",
  "hershey's dark chocolate",
  "hershey's kisses",
  "hershey’s kissables",
  "hershey’s milk chocolate",
  "jawbreakers",
  "jelly beans",
  "jolly rancher",
  "joyjoy",
  "junior mints",
  "kale smoothie",
  "kinder bueno",
  "kinder happy hippo",
  "kit kat bar",
  "kittens",
  "laffytaffy",
  "lemonheads",
  "licorice",
  "lindt truffle",
  "lollipops",
  "m&ms",
  "malted milk balls",
  "maltesers",
  "mars",
  "mary jane",
  "marzipan",
  "maynards",
  "mike and ike",
  "milk duds",
  "milky way",
  "milky way midnight",
  "minibags of chips",
  "mint juleps",
  "mint kisses",
  "mint leaves",
  "mounds bar",
  "mr. goodbar",
  "necco wafers",
  "nerds",
  "nestle crunch",
  "now'n'laters",
  "nutrageous",
  "oh henry",
  "oreos",
  "payday bar",
  "peanut butter bars",
  "peanut butter jars",
  "peeps",
  "pencils",
  "pennies",
  "pixy stix",
  "pop rocks",
  "popcorn",
  "popcorn ball",
  "pretzels",
  "puppies",
  "raisinets",
  "reese's pieces",
  "reese’s peanut butter cups",
  "reggie jackson bar",
  "ribbon candy",
  "ring pops",
  "rockets",
  "rocks",
  "rolos",
  "runts",
  "salt water taffy",
  "senior mints",
  "sixlets",
  "skittles",
  "skor bar",
  "smarties",
  "snickers bar",
  "soda",
  "sour patch kids",
  "starburst",
  "stickers",
  "sugar babies",
  "sugar daddy",
  "swedish fish",
  "sweetarts",
  "sweetums",
  "take 5 bar",
  "those odd marshmallow circus peanut things",
  "three musketeers",
  "tic tacs",
  "toblerone bar",
  "tootsie pops",
  "tootsie roll",
  "trail mix",
  "turkish delight",
  "twix bar",
  "twizzlers",
  "warheads",
  "wax lips",
  "whatchamacallit bar",
  "white chocolate",
  "whoppers",
  "wunderbar",
  "york peppermint patties",
  "zagnut bar",
  "zero bar"
)
