candy_list <- list(
  "100 grand bar" = c("100 grand bar",
                      "x100 grand bar"),
  "5th avenue bar" = c("5th avenue",
                       "5th avenue bar"),
  "aero bar" = c("aero",
                 "aero bars"),
  "almond joy bar" = c("almond joy",
                       "almond joys"),
  "babe ruth bar" = c("babe ruth",
                      "baby ruth",
                      "baby ruth bar",
                      "baby ruths"),
  "bit-o-honey" = c("bit o honey",
                    "bit o' honey",
                    "bit o'honey",
                    "bit-o-honey"),
  "bonkers" = c("bonkers",
                "bonkers the candy"),
  "candy apple" = c("candy apple",
                    "candy apples"),
  "caramel apple" = c("caramel apple",
                      "caramel apple pops",
                      "caramel apples",
                      "carmel apples"),
  "charleston chew" = c("charleston chew",
                        "charleston chews"),
  "chick-o-sticks" = c("chick o sticks we don t know what that is"),
  "clark bar" = c("clark bar",
                  "clark bars"),
  "cow tales" = c("cow tails",
                  "cow tales"),
  "dum-dums" = c("dum dum",
                 "dumdums lollipops",
                 "dum dum lollipops",
                 "dumdums",
                 "dum dums",
                 "dum dum pops"),
  "free restaurant candy" = c("candy that is clearly just the stuff given out for free at restaurants"),
  "gummi worms" = c("gummi worms",
                    "gummy worms"),
  "gummy bears" = c("gummy bears straight up"),
  "jawbreakers" = c("jaw breakers",
                    "jawbreakers"),
  "jelly belly" = c("jelly bellies",
                    "jelly belly"),
  "jolly rancher" = c("jolly rancher bad flavor",
                      "jolly ranchers good flavor"),
  "licorice" = c("licorice",
                 "licorice not black",
                 "licorice yes black"),
  "mary jane" = c("anonymous brown globs that come in black and orange wrappers",
                  "anonymous brown globs that come in black and orange wrappers a k a mary janes",
                  "mary janes"),
  "m&ms" = c("blue m ms",
             "green party m ms",
             "independent m ms",
             "mint m ms",
             "peanut m m s",
             "red m ms",
             "regular m ms",
             "peanut butter m&m's",
             "peanut butter m&ms",
             "third party m ms"),
  "mallo cup" = c("mallo cups",
                  "mallow cups"),
  "mike and ike" = c("mike",
                     "mike & ike",
                     "mike & ikes",
                     "mike and ike",
                     "mike and ikes"),
  "mounds bar" = c("mounds",
                   "mounds bar",
                   "mounds bars"),
  "mr goodbar" = c("goodbar",
                   "mr",
                   "mr goodbar"),
  "payday bar" = c("pay day",
                   "payday",
                   "payday bar",
                   "payday bars"),
  "peanut butter bars" = c("peanut butter bars",
                           "peanut butter jars"),
  "popcorn ball" = c("popcorn ball",
                     "popcorn balls"),
  "raisins" = c("box o raisins",
                      "boxo raisins",
                      "raisins"),
  "raisinets" = c("raisinets",
                  "raisinettes"),
  "reeses pieces" = c("reece's pieces",
                      "reese's pieces",
                      "reeses pieces"),
  "skor bar" = c("skor",
                 "skor bar",
                 "skor bars"),
  "sky bar" = c("sky bar",
                "skybar"),
  "smarties" = c("smarties american",
                 "smarties commonwealth"),
  "sour patch kids" = c("sour patch kids",
                        "sourpatch kids",
                        "sourpatch kids i e abominations of nature"),
  "sugar daddy" = c("sugar daddies",
                    "sugar daddy"),
  "sweetarts" = c("sweetarts",
                  "sweettarts"),
  "sweetums" = c("sweet tarts",
                 "sweetums",
                 "sweetums a friend to diabetes"),
  "take 5 bar" = c("take 5",
                   "take 5 bar",
                   "take 5 bars",
                   "take five",
                   "take5"),
  "tolberone bar" = c("tolberone something or other"),
  "tootsie pop" = c("tootsie pop",
                    "tootsie pops"),
  "tootsie roll" = c("tootsie roll",
                     "tootsie roll pops",
                     "tootsie rolls"),
  "whatchamacallit bar" = c("whatchamacallit",
                            "whatchamacallit bars"),
  "zagnut bar" = c("zagnut",
                   "zagnut bars"),
  "zero bar" = c("zero",
                 "zero bar",
                 "zero bars")
)
