candy_names <- c(
  "100 grand bar",
  "5th avenue bar",
  "abba zabba",
  "aero",
  "airheads",
  "almond joy",
  "andes mints",
  "any full sized candy bar",
  "atomic fireballs",
  "babe ruth",
  "bit o'honey",
  "black jacks",
  "blow pops",
  "bonkers",
  "bottle caps",
  "bounty",
  "box o'raisins",
  "bubble gum",
  "butterfinger",
  "cadbury creme eggs",
  "candy apple",
  "candy cigarettes",
  "candy corn",
  "caramel apple",
  "caramellos",
  "caramels",
  "charleston chew",
  "chick o'sticks",
  "chiclets",
  "circus peanuts",
  "clark bar",
  "coffee crisp",
  "cow tales",
  "crispy crunch",
  "dark chocolate",
  "dark chocolate hershey",
  "dots",
  "dove bars",
  "dum-dums",
  "ferrero rocher",
  "free restaurant candy",
  "fun dip",
  "fuzzy peaches",
  "gobstoppers",
  "goo goo clusters",
  "good n plenty",
  "gum",
  "gum from baseball cards",
  "gummi worms",
  "gummy bears",
  "hard candy",
  "hershey s kissables",
  "hershey s milk chocolate",
  "hersheys dark chocolate",
  "hersheys kisses",
  "jawbreakers",
  "jelly beans",
  "jelly belly",
  "jolly rancher",
  "joy joy mit iodine",
  "junior mints",
  "kale smoothie",
  "kinder bueno",
  "kinder happy hippo",
  "kit kat",
  "kittens",
  "laffy taffy",
  "lemon heads",
  "licorice",
  "lindt truffle",
  "lollipops",
  "m&m",
  "mallo cup",
  "malted milk balls",
  "maltesers",
  "mars",
  "mary jane",
  "marzipan",
  "maynards",
  "mike and ike",
  "milk duds",
  "milky way",
  "milky way midnight",
  "minibags of chips",
  "mint juleps",
  "mint kisses",
  "mint leaves",
  "mounds bar",
  "mr goodbar",
  "necco wafers",
  "nerds",
  "nestle crunch",
  "nown laters",
  "nutrageous",
  "oh henry",
  "oreos",
  "payday bar",
  "peanut butter bars",
  "peeps",
  "pencils",
  "pennies",
  "pixy stix",
  "pop rocks",
  "popcorn",
  "popcorn ball",
  "pretzels",
  "puppies",
  "raisinets",
  "reese s peanut butter cups",
  "reeses pieces",
  "reggie jackson bar",
  "ribbon candy",
  "ring pops",
  "rockets",
  "rocks",
  "rolos",
  "runts",
  "salt water taffy",
  "senior mints",
  "sixlets",
  "skittles",
  "skor bar",
  "sky bar",
  "smarties",
  "snickers",
  "soda",
  "sour patch kids",
  "starburst",
  "stickers",
  "sugar babies",
  "sugar daddy",
  "swedish fish",
  "sweetarts",
  "sweetums",
  "take 5 bar",
  "those odd marshmallow circus peanut things",
  "three musketeers",
  "tic tacs",
  "tolberone",
  "tootsie pop",
  "tootsie roll",
  "trail mix",
  "turkish delight",
  "twix",
  "twizzlers",
  "warheads",
  "wax lips",
  "whatchamacallit",
  "white chocolate",
  "whoppers",
  "wunderbar",
  "york peppermint patties",
  "zagnut bar",
  "zero bar"
)
